import type { MenuBootstrapResponse } from "@/lib/api";

export const FRONTEND_OFFLINE_MENU_TABLE_ID = "offline-menu";
export const FRONTEND_OFFLINE_MENU_STORE_SLUG = "garsone-offline";

const image = (seed: string) =>
  `https://images.unsplash.com/${seed}?auto=format&fit=crop&w=900&q=80`;

export const isFrontendOfflineMenuPath = (tableCode?: string | null) =>
  (tableCode || "").trim().toLowerCase() === FRONTEND_OFFLINE_MENU_TABLE_ID;

export const getFrontendOfflineMenuBootstrap = (
  lang: "en" | "el" = "en"
): MenuBootstrapResponse => ({
  store: {
    id: "frontend-offline-store",
    name: lang === "el" ? "Demo Μενού Garsone" : "Garsone Demo Menu",
    slug: FRONTEND_OFFLINE_MENU_STORE_SLUG,
    currencyCode: "EUR",
    currencySymbol: "€",
    orderingMode: "waiter",
  },
  table: {
    id: FRONTEND_OFFLINE_MENU_TABLE_ID,
    label: "Demo",
  },
  menu: {
    categories: [
      {
        id: "offline-cat-coffee",
        title: "Coffee",
        titleEn: "Coffee",
        titleEl: "Καφές",
        imageUrl: image("photo-1509042239860-f550ce710b93"),
        sortOrder: 1,
      },
      {
        id: "offline-cat-brunch",
        title: "Brunch",
        titleEn: "Brunch",
        titleEl: "Brunch",
        imageUrl: image("photo-1525351484163-7529414344d8"),
        sortOrder: 2,
      },
      {
        id: "offline-cat-mains",
        title: "Mains",
        titleEn: "Mains",
        titleEl: "Κυρίως",
        imageUrl: image("photo-1546069901-ba9599a7e63c"),
        sortOrder: 3,
      },
      {
        id: "offline-cat-drinks",
        title: "Drinks",
        titleEn: "Drinks",
        titleEl: "Ποτά",
        imageUrl: image("photo-1544145945-f90425340c7e"),
        sortOrder: 4,
      },
    ],
    items: [
      {
        id: "offline-item-espresso",
        title: "Espresso",
        titleEn: "Espresso",
        titleEl: "Espresso",
        descriptionEn: "Single shot with a rich crema.",
        descriptionEl: "Μονή δόση με πλούσια κρέμα.",
        priceCents: 220,
        categoryId: "offline-cat-coffee",
        isAvailable: true,
        imageUrl: image("photo-1510707577719-ae7c14805e3a"),
      },
      {
        id: "offline-item-freddo-espresso",
        title: "Freddo Espresso",
        titleEn: "Freddo Espresso",
        titleEl: "Freddo Espresso",
        descriptionEn: "Greek iced espresso, shaken and bright.",
        descriptionEl: "Παγωμένος espresso, χτυπημένος και έντονος.",
        priceCents: 320,
        categoryId: "offline-cat-coffee",
        isAvailable: true,
        imageUrl: image("photo-1461023058943-07fcbe16d735"),
      },
      {
        id: "offline-item-cappuccino",
        title: "Cappuccino",
        titleEn: "Cappuccino",
        titleEl: "Cappuccino",
        descriptionEn: "Espresso, steamed milk and soft foam.",
        descriptionEl: "Espresso, ζεστό γάλα και αφρόγαλα.",
        priceCents: 360,
        categoryId: "offline-cat-coffee",
        isAvailable: true,
        imageUrl: image("photo-1534778101976-62847782c213"),
      },
      {
        id: "offline-item-avocado-toast",
        title: "Avocado Toast",
        titleEn: "Avocado Toast",
        titleEl: "Toast με αβοκάντο",
        descriptionEn: "Sourdough, avocado, lime, chili flakes.",
        descriptionEl: "Προζυμένιο ψωμί, αβοκάντο, lime, chili.",
        priceCents: 780,
        categoryId: "offline-cat-brunch",
        isAvailable: true,
        imageUrl: image("photo-1525351484163-7529414344d8"),
      },
      {
        id: "offline-item-pancakes",
        title: "Pancakes",
        titleEn: "Pancakes",
        titleEl: "Pancakes",
        descriptionEn: "Stacked pancakes with berries and maple syrup.",
        descriptionEl: "Pancakes με berries και σιρόπι maple.",
        priceCents: 850,
        categoryId: "offline-cat-brunch",
        isAvailable: true,
        imageUrl: image("photo-1528207776546-365bb710ee93"),
      },
      {
        id: "offline-item-caesar",
        title: "Chicken Caesar",
        titleEn: "Chicken Caesar",
        titleEl: "Caesar κοτόπουλο",
        descriptionEn: "Grilled chicken, romaine, parmesan, croutons.",
        descriptionEl: "Κοτόπουλο σχάρας, romaine, παρμεζάνα, κρουτόν.",
        priceCents: 980,
        categoryId: "offline-cat-mains",
        isAvailable: true,
        imageUrl: image("photo-1550304943-4f24f54ddde9"),
      },
      {
        id: "offline-item-smash-burger",
        title: "Smash Burger",
        titleEn: "Smash Burger",
        titleEl: "Smash Burger",
        descriptionEn: "Double beef patty, cheddar, pickles, house sauce.",
        descriptionEl: "Διπλό μοσχαρίσιο patty, cheddar, πίκλες, sauce.",
        priceCents: 1150,
        categoryId: "offline-cat-mains",
        isAvailable: true,
        imageUrl: image("photo-1568901346375-23c9450c58cd"),
      },
      {
        id: "offline-item-lemonade",
        title: "Fresh Lemonade",
        titleEn: "Fresh Lemonade",
        titleEl: "Σπιτική λεμονάδα",
        descriptionEn: "Lemon, mint and sparkling water.",
        descriptionEl: "Λεμόνι, μέντα και ανθρακούχο νερό.",
        priceCents: 420,
        categoryId: "offline-cat-drinks",
        isAvailable: true,
        imageUrl: image("photo-1523371683702-7a37655e042d"),
      },
      {
        id: "offline-item-spritz",
        title: "Aperol Spritz",
        titleEn: "Aperol Spritz",
        titleEl: "Aperol Spritz",
        descriptionEn: "Aperol, prosecco and soda over ice.",
        descriptionEl: "Aperol, prosecco και soda με πάγο.",
        priceCents: 850,
        categoryId: "offline-cat-drinks",
        isAvailable: true,
        imageUrl: image("photo-1560512823-829485b8bf24"),
      },
    ],
    modifiers: [],
    itemModifiers: [],
    updatedAt: "2026-06-27T00:00:00.000Z",
  },
});
