const en = {
  title: "Bills", bill: "Bill", back: "Back to dashboard", allTables: "All tables", table: "Table", visit: "Visit",
  loading: "Loading bills…", refresh: "Refresh", refreshing: "Refreshing…", search: "Find a table",
  open: "Open", closed: "Closed", requested: "Bill requested", noBills: "No open bills", noResults: "No matching tables",
  total: "Ordered", collected: "Collected", due: "Remaining", settled: "Settled", payment: "Payment",
  requestAt: "Requested", startedAt: "Opened", emptyVisit: "No items on this bill yet.", items: "Items", payments: "Payments",
  quantity: "Quantity", remainingQuantity: "Unpaid quantity", unitPrice: "Each", itemTotal: "Total", order: "Order",
  recordPayment: "Record payment", cash: "Cash", card: "Card terminal", full: "Remaining balance", amount: "Amount", byItems: "Selected items",
  paymentMethod: "Received via", paymentMode: "Apply payment to", receivedAmount: "Amount received", paymentHint: "Record money already received. Card payments must be completed on your terminal first.",
  amountInvalid: "Enter a valid amount with up to two decimal places.", amountTooLarge: "The amount exceeds the remaining balance.", selectItems: "Choose the items being paid for.",
  selectAll: "Select all", clearSelection: "Clear", selectedTotal: "Selected total", outstanding: "Unpaid", decrease: "Remove one", increase: "Add one",
  recordReceived: "Record received payment", recording: "Recording…", recorded: "Payment recorded", paymentRecorded: "The payment has been recorded on this bill.",
  noPayments: "No payments recorded yet.", received: "Received", reference: "Reference", cancel: "Cancel", done: "Done",
  close: "Close table", closeTitle: "Close this table?", closeDescription: "This bill is settled. Closing it starts a fresh bill for the next guests.",
  closedSuccess: "Table closed", closedHint: "This visit is closed. Its bill is available for reference.", closeUnpaid: "Settle the remaining balance before closing the table.",
  transfer: "Move table", transferTitle: "Move this visit", transferHint: "Orders and payments move together. Choose an empty table.", transferTarget: "Destination table", noEmptyTables: "No empty tables are available.", transferConfirm: "Move visit", moved: "Visit moved",
  unknownTitle: "Payment confirmation pending", unknownHint: "The venue may have recorded this payment. Check its status before recording another one.", checkPayment: "Check payment", retrySame: "Retry this payment", checking: "Checking…",
  notFound: "This payment has not been found. Retry the same payment to finish recording it safely.", storageError: "This browser cannot save payment recovery details. Allow local storage before recording a payment.",
  lostConnection: "Cannot reach the venue. Connect to its network and refresh.", stale: "Showing the last received bill. Refresh before making changes.",
  changed: "This bill changed. Review its updated balance before recording the payment.", rejected: "The change could not be saved. Refresh the bill and try again.",
  accessError: "You do not have access to these bills. Sign in with a staff account.", signIn: "Sign in", unavailable: "This bill is no longer available. Choose a table from the list.",
  paymentTime: "Recorded", externalCard: "Card payment received externally", partialHint: "Previous amount payments reduce the total balance. Item selections cannot exceed what remains.",
  billRequestHint: "These guests are ready for their bill.", pendingAction: "Checking the previous change…", requestClosed: "The visit is closed. Start a new order for the next guests.",
  viewBill: "Open bill", updated: "Updated", activeOrders: "Some orders are still being prepared or served.",
  legacy: "Earlier orders", legacyHint: "These orders predate table visits. Review them before adding unpaid orders to a current bill. Amounts use the venue's current currency.",
  adopt: "Add to current bill", adoptTitle: "Add these earlier orders?", adoptHint: "Only add orders that belong to the guests at this table. Previously paid orders are historical and do not count as money collected today.",
  legacyPaid: "Historical paid order · payment method unknown", legacyUnpaid: "Unassigned unpaid order", selectOrders: "Choose earlier orders", added: "Earlier orders added", actionUnknown: "The change may have been saved. Refresh and check the table before trying again.", noClosed: "No closed bills", loadingTables: "Loading tables…",
};

const el: typeof en = {
  title: "Λογαριασμοί", bill: "Λογαριασμός", back: "Πίσω στην αρχική", allTables: "Όλα τα τραπέζια", table: "Τραπέζι", visit: "Επίσκεψη",
  loading: "Φόρτωση λογαριασμών…", refresh: "Ανανέωση", refreshing: "Ανανέωση…", search: "Βρείτε τραπέζι",
  open: "Ανοιχτοί", closed: "Κλειστοί", requested: "Ζητήθηκε λογαριασμός", noBills: "Δεν υπάρχουν ανοιχτοί λογαριασμοί", noResults: "Δεν βρέθηκαν τραπέζια",
  total: "Παραγγελίες", collected: "Εισπράχθηκαν", due: "Υπόλοιπο", settled: "Εξοφλήθηκε", payment: "Πληρωμή",
  requestAt: "Ζητήθηκε", startedAt: "Άνοιξε", emptyVisit: "Δεν υπάρχουν ακόμη προϊόντα στον λογαριασμό.", items: "Προϊόντα", payments: "Πληρωμές",
  quantity: "Ποσότητα", remainingQuantity: "Ανεξόφλητη ποσότητα", unitPrice: "Ανά τεμάχιο", itemTotal: "Σύνολο", order: "Παραγγελία",
  recordPayment: "Καταχώριση πληρωμής", cash: "Μετρητά", card: "Τερματικό κάρτας", full: "Υπόλοιπο λογαριασμού", amount: "Ποσό", byItems: "Επιλεγμένα προϊόντα",
  paymentMethod: "Εισπράχθηκαν με", paymentMode: "Η πληρωμή αφορά", receivedAmount: "Ποσό που εισπράχθηκε", paymentHint: "Καταχωρίστε χρήματα που έχετε ήδη εισπράξει. Η πληρωμή με κάρτα πρέπει πρώτα να ολοκληρωθεί στο τερματικό σας.",
  amountInvalid: "Συμπληρώστε έγκυρο ποσό με έως δύο δεκαδικά ψηφία.", amountTooLarge: "Το ποσό υπερβαίνει το υπόλοιπο του λογαριασμού.", selectItems: "Επιλέξτε τα προϊόντα που εξοφλούνται.",
  selectAll: "Επιλογή όλων", clearSelection: "Καθαρισμός", selectedTotal: "Επιλεγμένο σύνολο", outstanding: "Ανεξόφλητα", decrease: "Αφαίρεση ενός", increase: "Προσθήκη ενός",
  recordReceived: "Καταχώριση είσπραξης", recording: "Καταχώριση…", recorded: "Η πληρωμή καταχωρίστηκε", paymentRecorded: "Η πληρωμή καταχωρίστηκε στον λογαριασμό.",
  noPayments: "Δεν έχουν καταχωριστεί πληρωμές.", received: "Εισπράχθηκαν", reference: "Αναφορά", cancel: "Ακύρωση", done: "Ολοκλήρωση",
  close: "Κλείσιμο τραπεζιού", closeTitle: "Κλείσιμο τραπεζιού;", closeDescription: "Ο λογαριασμός έχει εξοφληθεί. Με το κλείσιμο, οι επόμενοι πελάτες θα ξεκινήσουν νέο λογαριασμό.",
  closedSuccess: "Το τραπέζι έκλεισε", closedHint: "Η επίσκεψη έχει κλείσει. Ο λογαριασμός είναι διαθέσιμος για αναφορά.", closeUnpaid: "Εξοφλήστε το υπόλοιπο πριν κλείσετε το τραπέζι.",
  transfer: "Μεταφορά τραπεζιού", transferTitle: "Μεταφορά επίσκεψης", transferHint: "Παραγγελίες και πληρωμές μεταφέρονται μαζί. Επιλέξτε κενό τραπέζι.", transferTarget: "Νέο τραπέζι", noEmptyTables: "Δεν υπάρχουν διαθέσιμα κενά τραπέζια.", transferConfirm: "Μεταφορά επίσκεψης", moved: "Η επίσκεψη μεταφέρθηκε",
  unknownTitle: "Αναμονή επιβεβαίωσης πληρωμής", unknownHint: "Η πληρωμή μπορεί να έχει καταχωριστεί. Ελέγξτε την κατάστασή της πριν καταχωρίσετε άλλη.", checkPayment: "Έλεγχος πληρωμής", retrySame: "Επανάληψη ίδιας πληρωμής", checking: "Έλεγχος…",
  notFound: "Η πληρωμή δεν βρέθηκε. Επαναλάβετε την ίδια πληρωμή για να ολοκληρωθεί με ασφάλεια η καταχώριση.", storageError: "Ο περιηγητής δεν αποθηκεύει στοιχεία ανάκτησης πληρωμών. Επιτρέψτε την τοπική αποθήκευση πριν καταχωρίσετε πληρωμή.",
  lostConnection: "Δεν υπάρχει σύνδεση με το κατάστημα. Συνδεθείτε στο δίκτυό του και ανανεώστε.", stale: "Εμφανίζεται η τελευταία γνωστή κατάσταση. Ανανεώστε πριν κάνετε αλλαγές.",
  changed: "Ο λογαριασμός άλλαξε. Ελέγξτε το νέο υπόλοιπο πριν καταχωρίσετε την πληρωμή.", rejected: "Η αλλαγή δεν αποθηκεύτηκε. Ανανεώστε τον λογαριασμό και δοκιμάστε ξανά.",
  accessError: "Δεν έχετε πρόσβαση στους λογαριασμούς. Συνδεθείτε με λογαριασμό προσωπικού.", signIn: "Σύνδεση", unavailable: "Ο λογαριασμός δεν είναι πλέον διαθέσιμος. Επιλέξτε τραπέζι από τη λίστα.",
  paymentTime: "Καταχωρίστηκε", externalCard: "Η κάρτα χρεώθηκε εξωτερικά", partialHint: "Οι προηγούμενες πληρωμές ποσού μειώνουν το συνολικό υπόλοιπο. Η επιλογή προϊόντων δεν μπορεί να το υπερβαίνει.",
  billRequestHint: "Οι πελάτες είναι έτοιμοι για τον λογαριασμό.", pendingAction: "Έλεγχος προηγούμενης αλλαγής…", requestClosed: "Η επίσκεψη έκλεισε. Ξεκινήστε νέα παραγγελία για τους επόμενους πελάτες.",
  viewBill: "Άνοιγμα λογαριασμού", updated: "Ενημέρωση", activeOrders: "Ορισμένες παραγγελίες ετοιμάζονται ή εξυπηρετούνται ακόμη.",
  legacy: "Παλαιότερες παραγγελίες", legacyHint: "Αυτές οι παραγγελίες προϋπήρχαν των επισκέψεων. Ελέγξτε τες πριν προσθέσετε ανεξόφλητες σε τρέχοντα λογαριασμό. Τα ποσά εμφανίζονται στο τρέχον νόμισμα του καταστήματος.",
  adopt: "Προσθήκη στον λογαριασμό", adoptTitle: "Προσθήκη παλαιότερων παραγγελιών;", adoptHint: "Προσθέστε μόνο παραγγελίες των πελατών που βρίσκονται τώρα στο τραπέζι. Οι ήδη πληρωμένες είναι ιστορικές και δεν προσμετρώνται στις σημερινές εισπράξεις.",
  legacyPaid: "Ιστορική εξόφληση · άγνωστος τρόπος πληρωμής", legacyUnpaid: "Ανεξόφλητη χωρίς επίσκεψη", selectOrders: "Επιλέξτε παλαιότερες παραγγελίες", added: "Οι παραγγελίες προστέθηκαν", actionUnknown: "Η αλλαγή μπορεί να έχει αποθηκευτεί. Ανανεώστε και ελέγξτε το τραπέζι πριν επαναλάβετε.", noClosed: "Δεν υπάρχουν κλειστοί λογαριασμοί", loadingTables: "Φόρτωση τραπεζιών…",
};

export const billingCopy = { en, el };
