const en = {
  title: "Local operations", back: "Back to manager", refresh: "Refresh", loading: "Checking the venue…",
  updated: "Checked", unavailable: "Local operations are available on the venue's Pi.",
  loadError: "Cannot reach the venue. Connect to its Wi-Fi and refresh.", stale: "Showing the last received status.",
  reconnect: "Connection lost", accessError: "Your session cannot access this page. Sign in again.", signIn: "Sign in",
  printers: "Printers", printer: "Printer", deviceAvailable: "Device available", deviceMissing: "Device unavailable",
  printing: "Printing", printerHint: "A device can be available while the printer is off or out of paper. Check the test ticket.",
  test: "Test print", printingDisabled: "Local printing is disabled.", noPrinters: "No local printers configured.",
  needsCheck: "Check these tickets", uncertainHint: "The printer may have printed these tickets. Check the paper before sending another copy.",
  alreadyPrinted: "Already printed", reprint: "Reprint", waiting: "Waiting to print", sending: "Sending to printer",
  queued: "Queued", sent: "Sent to printer", ticket: "Ticket", table: "Table", testTicket: "Print job", copy: "Reprint",
  checkedPrinted: "Confirmed by staff", reprintRequested: "Replacement requested", history: "Recent activity",
  noJobs: "No tickets waiting", pending: "Waiting", uncertain: "To check", system: "Venue system",
  database: "Database", databaseOk: "Responding", databaseError: "Not responding", storage: "Free storage",
  backup: "Last backup", unknown: "Not reported", backupHint: "Backups are taken before Core updates. Orders since then are not included.",
  backupMissing: "No successful backup has been reported.", backupOld: "More than 24 hours ago", uptime: "App uptime",
  day: "d", hour: "h", minute: "min", now: "Just now", details: "Technical details", testTitle: "Print a test ticket?",
  testDescription: "This sends one test ticket to the selected printer. Check that the paper comes out clearly.",
  printedTitle: "Is this ticket on paper?", printedDescription: "Mark it resolved only after checking the complete ticket was printed.",
  reprintTitle: "Print another copy?", reprintDescription: "Check the printer and paper first. The original may already have printed. This sends a new ticket marked as a reprint.",
  confirmPrinted: "Yes, it printed", confirmReprint: "Print another copy", cancel: "Cancel", working: "Saving…",
  actionError: "No confirmation received. Refresh the status or retry this same action safely.",
  actionConflict: "This ticket changed. Refresh the status before taking another action.",
  actionRejected: "The action could not be completed. Check the printer and refresh the status.",
  testSuccess: "Test queued. Check the paper at the printer.", printedSuccess: "Ticket marked as printed.",
  reprintSuccess: "Another copy is queued. Check the paper at the printer.", retry: "Retry action", refreshing: "Refreshing…",
  processingHint: "Wait for printing to finish before checking this ticket.", oldSnapshot: "Status is out of date. Refresh to enable actions.",
  queueUnavailable: "Print queue unavailable. Refresh to check the tickets.",
  pendingLimit: "Showing {shown} of {total} pending tickets. Tickets that need checking appear first.",
};

const el: typeof en = {
  title: "Τοπική λειτουργία", back: "Πίσω στη διαχείριση", refresh: "Ανανέωση", loading: "Έλεγχος καταστήματος…",
  updated: "Έλεγχος", unavailable: "Η τοπική λειτουργία είναι διαθέσιμη στο Pi του καταστήματος.",
  loadError: "Δεν υπάρχει σύνδεση με το κατάστημα. Συνδεθείτε στο Wi-Fi του και ανανεώστε.", stale: "Εμφανίζεται η τελευταία γνωστή κατάσταση.",
  reconnect: "Η σύνδεση χάθηκε", accessError: "Η συνεδρία σας δεν έχει πρόσβαση σε αυτή τη σελίδα. Συνδεθείτε ξανά.", signIn: "Σύνδεση",
  printers: "Εκτυπωτές", printer: "Εκτυπωτής", deviceAvailable: "Διαθέσιμη συσκευή", deviceMissing: "Μη διαθέσιμη συσκευή",
  printing: "Εκτύπωση", printerHint: "Η συσκευή μπορεί να εμφανίζεται διαθέσιμη ακόμη κι αν ο εκτυπωτής είναι κλειστός ή χωρίς χαρτί. Ελέγξτε τη δοκιμαστική εκτύπωση.",
  test: "Δοκιμή εκτύπωσης", printingDisabled: "Η τοπική εκτύπωση είναι απενεργοποιημένη.", noPrinters: "Δεν έχουν ρυθμιστεί τοπικοί εκτυπωτές.",
  needsCheck: "Ελέγξτε τις εκτυπώσεις", uncertainHint: "Αυτά τα δελτία μπορεί να έχουν ήδη εκτυπωθεί. Ελέγξτε το χαρτί πριν στείλετε νέο αντίγραφο.",
  alreadyPrinted: "Έχει εκτυπωθεί", reprint: "Επανεκτύπωση", waiting: "Σε αναμονή εκτύπωσης", sending: "Αποστολή στον εκτυπωτή",
  queued: "Σε αναμονή", sent: "Στάλθηκε στον εκτυπωτή", ticket: "Δελτίο", table: "Τραπέζι", testTicket: "Εργασία εκτύπωσης", copy: "Επανεκτύπωση",
  checkedPrinted: "Επιβεβαίωση προσωπικού", reprintRequested: "Ζητήθηκε νέο αντίγραφο", history: "Πρόσφατη δραστηριότητα",
  noJobs: "Δεν υπάρχουν δελτία σε αναμονή", pending: "Αναμονή", uncertain: "Για έλεγχο", system: "Σύστημα καταστήματος",
  database: "Βάση δεδομένων", databaseOk: "Αποκρίνεται", databaseError: "Δεν αποκρίνεται", storage: "Ελεύθερος χώρος",
  backup: "Τελευταίο αντίγραφο", unknown: "Δεν αναφέρεται", backupHint: "Τα αντίγραφα λαμβάνονται πριν από ενημερώσεις του Core. Μεταγενέστερες παραγγελίες δεν περιλαμβάνονται.",
  backupMissing: "Δεν έχει αναφερθεί επιτυχές αντίγραφο ασφαλείας.", backupOld: "Πάνω από 24 ώρες πριν", uptime: "Χρόνος λειτουργίας",
  day: "ημ.", hour: "ώρ.", minute: "λεπ.", now: "Μόλις τώρα", details: "Τεχνικές λεπτομέρειες", testTitle: "Δοκιμαστική εκτύπωση;",
  testDescription: "Θα σταλεί ένα δοκιμαστικό δελτίο στον επιλεγμένο εκτυπωτή. Ελέγξτε ότι εκτυπώνεται καθαρά.",
  printedTitle: "Έχει εκτυπωθεί το δελτίο;", printedDescription: "Επιβεβαιώστε μόνο αφού ελέγξετε ότι έχει εκτυπωθεί ολόκληρο το δελτίο.",
  reprintTitle: "Νέο αντίγραφο;", reprintDescription: "Ελέγξτε πρώτα τον εκτυπωτή και το χαρτί. Το αρχικό μπορεί να έχει ήδη εκτυπωθεί. Θα σταλεί νέο δελτίο με ένδειξη επανεκτύπωσης.",
  confirmPrinted: "Ναι, εκτυπώθηκε", confirmReprint: "Εκτύπωση νέου αντιγράφου", cancel: "Ακύρωση", working: "Αποθήκευση…",
  actionError: "Δεν ελήφθη επιβεβαίωση. Ανανεώστε την κατάσταση ή επαναλάβετε με ασφάλεια την ίδια ενέργεια.",
  actionConflict: "Το δελτίο άλλαξε. Ανανεώστε την κατάσταση πριν συνεχίσετε.",
  actionRejected: "Η ενέργεια δεν ολοκληρώθηκε. Ελέγξτε τον εκτυπωτή και ανανεώστε την κατάσταση.",
  testSuccess: "Η δοκιμή μπήκε σε αναμονή. Ελέγξτε το χαρτί στον εκτυπωτή.", printedSuccess: "Το δελτίο επιβεβαιώθηκε ως εκτυπωμένο.",
  reprintSuccess: "Το νέο αντίγραφο μπήκε σε αναμονή. Ελέγξτε το χαρτί στον εκτυπωτή.", retry: "Επανάληψη ενέργειας", refreshing: "Ανανέωση…",
  processingHint: "Περιμένετε να τελειώσει η εκτύπωση πριν ελέγξετε το δελτίο.", oldSnapshot: "Η κατάσταση δεν είναι πρόσφατη. Ανανεώστε για να ενεργοποιηθούν οι ενέργειες.",
  queueUnavailable: "Η ουρά εκτύπωσης δεν είναι διαθέσιμη. Ανανεώστε για να ελέγξετε τα δελτία.",
  pendingLimit: "Εμφανίζονται {shown} από {total} δελτία σε εκκρεμότητα. Προηγούνται όσα χρειάζονται έλεγχο.",
};

export const localOperationsCopy = { en, el };
